name: End-to-End Test
on:
  push:
    branches: ["main"]

jobs:
  test:
    name: Run TestCafe Tests
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        with:
            args: "-v"
      - name: Run custom runner
        run: node runner_se.js
        
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: reporter # The folder the action should deploy.
          target-folder: example2
